/*
  Highcharts JS v5.0.0 (2016-09-29)
 Solid angular gauge module

 (c) 2010-2016 Torstein Honsi

 License: www.highcharts.com/license
*/

(function(e){"object"==typeof module&&module.exports?module.exports=e:e(Highcharts)})(function(e){(function(e){var t=e.pInt,n=e.pick,r=e.each,i=e.isNumber,s;s={initDataClasses:function(t){var n=this,i=this.chart,s,o=0,u=this.options;this.dataClasses=s=[],r(t.dataClasses,function(r,f){var p;r=e.merge(r),s.push(r),r.color||("category"===u.dataClassColor?(p=i.options.colors,r.color=p[o++],o===p.length&&(o=0)):r.color=n.tweenColors(e.color(u.minColor),e.color(u.maxColor),f/(t.dataClasses.length-1)))})},initStops:function(t){this.stops=t.stops||[[0,this.options.minColor],[1,this.options.maxColor]],r(this.stops,function(t){t.color=e.color(t[1])})},toColor:function(e,t){var n,r=this.stops,i,s=this.dataClasses,o,u;if(s){for(u=s.length;u--;)if(o=s[u],i=o.from,r=o.to,(void 0===i||e>=i)&&(void 0===r||e<=r)){n=o.color,t&&(t.dataClass=u);break}}else{this.isLog&&(e=this.val2lin(e)),n=1-(this.max-e)/(this.max-this.min);for(u=r.length;u--&&!(n>r[u][0]););i=r[u]||r[u+1],r=r[u+1]||i,n=1-(r[0]-n)/(r[0]-i[0]||1),n=this.tweenColors(i.color,r.color,n)}return n},tweenColors:function(e,t,n){var r;return t.rgba.length&&e.rgba.length?(e=e.rgba,t=t.rgba,r=1!==t[3]||1!==e[3],e=(r?"rgba(":"rgb(")+Math.round(t[0]+(e[0]-t[0])*(1-n))+","+Math.round(t[1]+(e[1]-t[1])*(1-n))+","+Math.round(t[2]+(e[2]-t[2])*(1-n))+(r?","+(t[3]+(e[3]-t[3])*(1-n)):"")+")"):e=t.input||"none",e}},r(["fill","stroke"],function(t){e.Fx.prototype[t+"Setter"]=function(){this.elem.attr(t,s.tweenColors(e.color(this.start),e.color(this.end),this.pos))}}),e.seriesType("solidgauge","gauge",{colorByPoint:!0},{bindAxes:function(){var t;e.seriesTypes.gauge.prototype.bindAxes.call(this),t=this.yAxis,e.extend(t,s),t.options.dataClasses&&t.initDataClasses(t.options),t.initStops(t.options)},drawPoints:function(){var e=this,s=e.yAxis,o=s.center,a=e.options,l=e.chart.renderer,c=a.overshoot,h=i(c)?c/180*Math.PI:0;r(e.points,function(r){var i=r.graphic,c=s.startAngleRad+s.translate(r.y,null,null,null,!0),p=t(n(r.options.radius,a.radius,100))*o[2]/200,d=t(n(r.options.innerRadius,a.innerRadius,60))*o[2]/200,v=s.toColor(r.y,r),m=Math.min(s.startAngleRad,s.endAngleRad),y=Math.max(s.startAngleRad,s.endAngleRad);"none"===v&&(v=r.color||e.color||"none"),"none"!==v&&(r.color=v),c=Math.max(m-h,Math.min(y+h,c)),!1===a.wrap&&(c=Math.max(m,Math.min(y,c))),m=Math.min(c,s.startAngleRad),c=Math.max(c,s.startAngleRad),c-m>2*Math.PI&&(c=m+2*Math.PI),r.shapeArgs=d={x:o[0],y:o[1],r:p,innerR:d,start:m,end:c,fill:v},r.startR=p,i?(r=d.d,i.animate(d),r&&(d.d=r)):r.graphic=l.arc(d).addClass("highcharts-point").attr({fill:v,"sweep-flag":0}).add(e.group)})},animate:function(t){t||(this.startAngleRad=this.yAxis.startAngleRad,e.seriesTypes.pie.prototype.animate.call(this,t))}})})(e)});